name: evo-design
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
- python=3.11
- pytorch
- pytorch-cuda=11.8
- pip
- pip:
  - evo-model
  - pandas
  - datasets  # HuggingFace datasets library
